### ISSUE TITLE
Strong Name for fizzler.Systems.HtmlAgilityPack.dll

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/Fizzler#53]
Add strong name for `Fizzler.Systems.HtmlAgilityPack.dll`

Most of the projects build failed because of this assembly hasn't a strong name. It will be quite useful for most of users.

---
Reported by `RuwankaMadhushan` on 2014-08-28 06:13:52

---
 * *Attachment: Capturefizz.PNG<br>![Capturefizz.PNG](https://cloud.githubusercontent.com/assets/20511/9428380/e12100fc-49ac-11e5-80fe-f384e683147e.PNG)*

**Comment by alexeysuvorov** [comment]
Any reason why you don't allow to make pull requests?

**Comment by atifaziz** [comment]
@alexeysuvorov Because, in general, it is a lot of trouble and generally not worth the gains:

* [Signing WebActivator](https://github.com/davidebbo/WebActivator/wiki/Signing-WebActivator)
* [Json.NET Strong Naming and Assembly Version Numbers](http://james.newtonking.com/archive/2012/04/04/json-net-strong-naming-and-assembly-version-numbers)
* [JSON.NET Strong Naming And NuGet Woes](http://nickberardi.com/json-net-strong-naming-and-nuget-woes/)
* [FubuMVC Lessons Learned — Strong Naming Woes and Workarounds](http://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/)
