### ISSUE TITLE
No info about license

### ISSUE THREAD

**Issue by alexeysuvorov** [atifaziz/Fizzler#55]
Please add information about license to readme. It is quite important for your enterprise users.

**Comment by atifaziz** [comment]
@alexeysuvorov It's already there. See [`COPYING.LESSER.txt`][COPYING.LESSER] and [`COPYING.txt`][COPYING]. It's quite customary in open source projects to have just those files. The [Fizzler][Fizzler.nupkg] and [Fizzler.Systems.HtmlAgilityPack][Fizzler.Systems.HtmlAgilityPack.nupkg] NuGet packages also have direct pointers to the [LGPL license][lgpl]. Are you saying it's not obvious in spite of this?


[COPYING.LESSER]: https://github.com/atifaziz/Fizzler/blob/5355241883f049768c73623f979dce755678d984/COPYING.LESSER.txt
[COPYING]: https://github.com/atifaziz/Fizzler/blob/5355241883f049768c73623f979dce755678d984/COPYING.txt
[Fizzler.Systems.HtmlAgilityPack.nupkg]: https://www.nuget.org/packages/Fizzler.Systems.HtmlAgilityPack/
[Fizzler.nupkg]: https://www.nuget.org/packages/Fizzler/
[lgpl]: http://www.gnu.org/licenses/lgpl.html

**Comment by atifaziz** [comment]
Closing due to no further feedback.

**Comment by JensNordenbro** [comment]
any chance @atifaziz to turns this into MIT ? :)

**Comment by atifaziz** [comment]
@JensNordenbro This is a closed issue, so kindly [open/start a new discussion](https://github.com/atifaziz/Fizzler/discussions/categories/q-a) instead.
