### ISSUE TITLE
How to select all nodes with class and specific embedded style attribute

### ISSUE THREAD

**Issue by underwater** [atifaziz/Fizzler#57]
Just starting out with this library, and trying to extract all the elements in an html doc, that have a specific class name, and that also have a style attribute that has a specific inline defined value.

My elements are inside a hierarchy that looks like this
`body > table > tbody > tr  > td  `

The collection of p elements I am interested look like this 

`<p class="s11" style="padding-top: 1pt;padding-left: 1pt;text-indent: 0pt;line-height: 8pt;text-align: left;"> MY TEXT </p>`

Any guidance would be appreciated

**Comment by atifaziz** [comment]
You can get to the paragraph elements using `p.s11[style]`. This will get you all `p` elements with the class `s11` and some attribute `style`. Then if you want to further refine the selection based on the actual content of the `style` attribute then you could continue to that in LINQ. Here's an example doing just that if the `style` attribute has CSS property named `text-align` with a value of `left`:

```c#
var q = 
    from e in doc.DocumentNode.QuerySelectorAll("p.s11[style]")
    where e.GetAttributeValue("style", string.Empty)
           .Split(';')
           .Select(p => p.Split(new[] { ':' }, 2))
           .Where(p => p.Length == 2)
           .Select(p => new { Name = p[0].Trim(), Value = p[1].Trim() })
           .Any(p => p.Name == "text-align" && p.Value == "left")
    select e;
```

Another option is to use regular expressions:

```c#
var q = 
    from e in doc.DocumentNode.QuerySelectorAll("p.s11[style]")
    where Regex.IsMatch(e.GetAttributeValue("style", string.Empty), @"\btext-align\s*:\s*left\b")
    select e;
```

**Comment by underwater** [comment]
That does handle exactly what I need,

I very much appreciate your really valuable help,

Indeed an awesome package 😊
