### ISSUE TITLE
Fizzler 1.1.0 was restored using `.NETFrameworkmVersion=v4.6.1` in a project targeting `.NETCoreApp 2.0`

### ISSUE THREAD

**Issue by danielcrenna** [atifaziz/Fizzler#62]
While I see the source code is set to support netstandard1.0, it appears the NuGet releases do not contain the correct .DLLs when restored.

**Comment by atifaziz** [comment]
I'm seeing the same and it's strange. Meanwhile, thanks for reporting this.

**Comment by atifaziz** [comment]
Silly of me to forget but the .NET Standard 1.0 target was addressed in #60 and is [slated for 1.2](https://github.com/atifaziz/Fizzler/milestone/1?closed=1) which hasn't been released yet. I think I can schedule it for end of this month, which is just a couple of days away.

**Comment by atifaziz** [comment]
@danielcrenna This is now addressed with the [1.2 release](https://github.com/atifaziz/Fizzler/releases/tag/v1.2.0).
