### ISSUE TITLE
Does Fizzler support .net core?

### ISSUE THREAD

**Issue by raiytu4** [atifaziz/Fizzler#65]
Hi,

Recently I try out Fizzler on my .net core project, it working perfectly, but in the dependence section I saw a warning message said that this library targeting .net framework 4.6 that may not fully compatible with my project. Do I have to worry about it?

**Comment by atifaziz** [comment]
If you are using [version 1.2](https://github.com/atifaziz/Fizzler/releases/tag/v1.2.0), then yes, it was specifically designed to target .NET Standard, which include .NET Core.

In terms of packages, are you talking about Fizzler.Systems.HtmlAgilityPack by chance or just Fizzler?

**Comment by raiytu4** [comment]
Thank for the support, I just include the pre-release checkbox an install the 1.2 version. The warning is gone. This is a great library, keep up the good work!

**Comment by atifaziz** [comment]
> I just include the pre-release checkbox an install the 1.2 version

That's odd because 1.2 isn't a pre-release; it's been released since February of this year.

**Comment by raiytu4** [comment]
![capture](https://user-images.githubusercontent.com/25586304/41499590-a9ce19b6-71ac-11e8-92ac-b9bd34e6f9ef.PNG)
well, it shows up as 1.2 prerelease for me, better check that out

**Comment by atifaziz** [comment]
So yeah, seems you're talking about Fizzler.Systems.HtmlAgilityPack instead and the .NET Standard version for that package is a [pre-release (i.e. 1.2.0-rc-1)](https://www.nuget.org/packages/Fizzler.Systems.HtmlAgilityPack/1.2.0-rc-1).
