### ISSUE TITLE
Ship with PDB on NuGet package

### ISSUE THREAD

**Issue by AraHaan** [atifaziz/Fizzler#76]
I would love it to when I consume the vvvv/SVG library (the github public fork of SVG.NET that is actively maintained, that my built binaries would have entirely portable pdb for Fizzler.

Currently these is no pdb or any usage of the ``SourceLink.Github`` package so that way if there is an odd rare case exception that visual studio 2019 would then start downloading the sources from this repository to Fizzler to use to show where the exception comes from.

This information could help then track now possible bugs in Fizzler and squash them.

**Comment by atifaziz** [comment]
Fair.

**Comment by atifaziz** [comment]
Fix published with [release 1.2.1](https://github.com/atifaziz/Fizzler/releases/tag/v1.2.1).
