### ISSUE TITLE
QuerySelectorAll not locating elements that can be found with document.querySelectorAll('')

### ISSUE THREAD

**Issue by JaxonBest** [atifaziz/Fizzler#81]
Hello, I started using Fizzler yesterday and all was fine until I was trying to select multiple elements using a long query selector and Fizzler wasn't able to locate the elements I was expecting. Just to make sure I didn't create an invalid selector I used the chrome dev tools and used the `document.querySelectorAll()` function and it returned a full list of all the elements as expected.

The Query Selector I was using is the following: `.fotorama__nav__shaft>.fotorama__nav__frame--thumb>.fotorama__thumb>img`.
Chrome returned 5 results all **img** tags. While Fizzler returned 0. 

Am I doing something incorrectly or is this a somehow a bug?

**Comment by atifaziz** [comment]
I am guessing you are using **[Fizzler.Systems.HtmlAgilityPack](https://www.nuget.org/packages/Fizzler.Systems.HtmlAgilityPack/)**? If so, that depends on **[HtmlAgilityPack](https://www.nuget.org/packages/HtmlAgilityPack/)** (1.5.1) so we'd first have to first determine whether the bug exists in the former or the later. You see, if **HtmlAgilityPack** parses the HTML incorrectly then the selector may not find the nodes at the right places. A quick test would be to reference the [latest version of **HtmlAgilityPack**](https://www.nuget.org/packages/HtmlAgilityPack/1.11.43) and see if the bug still persists or not.

**Comment by atifaziz** [comment]
[Closing as stale](https://github.com/atifaziz/Fizzler/issues/81#event-13460030802) due to no follow-up.
